#!/bin/bash
set -eu

runner_name=${1}
runner_host=${2}
runner_token=${3}
runner_image=${4}

export DEBIAN_FRONTEND=noninteractive
## Install docker
curl -sSL https://get.docker.com/ | sh
usermod -aG docker ubuntu

## Install GitLab Multi-Runner
curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | bash
apt-get install gitlab-ci-multi-runner
# Configure runner
gitlab-ci-multi-runner register \
  --non-interactive \
  --url ${runner_host} \
  --registration-token ${runner_token} \
  --name ${runner_name} \
  --executor docker \
  --docker-image ${runner_image} 2>&1 >> /var/log/gitlab-ci-multi-runner.boostrap.log
